spring:
  application:
    name: manus
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/ragdb
    username:
    password:
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
langchain4j:
  embedding-model:
    open-ai:
      base-url: http://127.0.0.1:8000/v1
      model-name: shibing624/text2vec-base-chinese
  open-ai:
    chat-model:
      api-key:
      base-url:
      model-name:
  reranker:
    http:
      url: http://127.0.0.1:8001/rerank

# 应用配置
app:
  file:
    upload-dir: ./uploads

# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false

# Knife4j配置
knife4j:
  enable: true
  openapi:
    title: Manus API Documentation
    description: 基于Sa-Token的用户权限管理系统API文档
    email: admin@example.com
    concat: Admin
    url: https://example.com
    version: v1.0.0
    license: Apache 2.0
    license-url: https://www.apache.org/licenses/LICENSE-2.0.html
    terms-of-service-url: https://example.com/terms
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.example.manus.controller


